version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - cd blog-frontend
      - npm install

  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*'
